// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CreateBook: typeof import('./src/components/createBook/CreateBook.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LayoutFooter: typeof import('./src/components/layout/LayoutFooter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserCard: typeof import('./src/views/user/components/UserCard.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPopover: typeof import('vant/es')['Popover']
    VanUploader: typeof import('vant/es')['Uploader']
  }
}
